
import type { PortfolioItem } from '@/components/landing/Portfolio';

export const placeholderProjects: Omit<PortfolioItem, 'id'>[] = [
    {
      title: 'QuantumLeap CRM',
      slug: 'quantumleap-crm',
      description: 'A futuristic CRM dashboard design with a focus on data visualization and user experience.',
      fullDescription: 'QuantumLeap CRM is a conceptual project aimed at reimagining the customer relationship management experience. The design features a dark, vibrant interface with interactive charts and an AI-powered assistant to provide insights and automate tasks. The goal was to create a tool that is not only powerful but also a joy to use.',
      image: 'https://picsum.photos/seed/quantum/1200/800',
      hint: 'dashboard futuristic',
      tags: ['UI/UX', 'Figma', 'Dashboard', 'Concept'],
      category: 'design',
      link: '#',
      screenshots: [
        'https://picsum.photos/seed/quantum-s1/1200/800',
        'https://picsum.photos/seed/quantum-s2/1200/800',
        'https://picsum.photos/seed/quantum-s3/1200/800',
      ],
    },
    {
      title: 'Aura Meditation App',
      slug: 'aura-meditation',
      description: 'A calming and intuitive mobile app for guided meditation and mindfulness exercises.',
      fullDescription: 'Aura is a mobile application designed to help users find peace and mindfulness in their daily lives. The app features a library of guided meditations, breathing exercises, and calming soundscapes. The user interface is minimal and serene, using soft colors and smooth animations to create a tranquil experience.',
      image: 'https://picsum.photos/seed/aura/1200/800',
      hint: 'mobile wellness',
      tags: ['Mobile App', 'React Native', 'UI/UX', 'Wellness'],
      category: 'mobile',
      link: '#',
      screenshots: [
        'https://picsum.photos/seed/aura-s1/800/1200',
        'https://picsum.photos/seed/aura-s2/800/1200',
        'https://picsum.photos/seed/aura-s3/800/1200',
      ],
    },
    {
      title: 'NovaMart E-commerce',
      slug: 'novamart-ecommerce',
      description: 'A modern, full-featured e-commerce website built with Next.js and Tailwind CSS.',
      fullDescription: 'NovaMart is a complete e-commerce solution with a clean, user-friendly interface. It includes features like product filtering, a secure checkout process with Stripe integration, user accounts, and an admin dashboard for managing products and orders. The site is fully responsive and optimized for performance.',
      image: 'https://picsum.photos/seed/novamart/1200/800',
      hint: 'website shopping',
      tags: ['Next.js', 'React', 'Stripe', 'Web Development'],
      category: 'web',
      link: '#',
      screenshots: [
        'https://picsum.photos/seed/novamart-s1/1200/800',
        'https://picsum.photos/seed/novamart-s2/1200/800',
        'https://picsum.photos/seed/novamart-s3/1200/800',
      ],
    },
    {
      title: 'Helios Branding',
      slug: 'helios-branding',
      description: 'A complete brand identity for a renewable energy company, from logo to style guide.',
      fullDescription: 'Helios is a branding project for a fictional solar energy company. The identity is built around the concepts of light, energy, and sustainability. The project included logo design, color palette selection, typography, and a comprehensive brand guidelines document.',
      image: 'https://picsum.photos/seed/helios/1200/800',
      hint: 'logo modern',
      tags: ['Branding', 'Logo Design', 'Illustrator', 'Visual Identity'],
      category: 'design',
      link: '#',
      screenshots: [
        'https://picsum.photos/seed/helios-s1/1200/800',
        'https://picsum.photos/seed/helios-s2/1200/800',
      ],
    },
    {
      title: 'Travelly App',
      slug: 'travelly-app',
      description: 'A social travel planning app that helps users discover and plan trips with friends.',
      fullDescription: 'Travelly is a mobile app that makes trip planning a collaborative and enjoyable experience. Users can create trip itineraries, invite friends, and discover new destinations. The app integrates with mapping services and features a real-time chat for seamless communication.',
      image: 'https://picsum.photos/seed/travelly/1200/800',
      hint: 'mobile travel',
      tags: ['iOS', 'SwiftUI', 'Firebase', 'Mobile App'],
      category: 'mobile',
      link: '#',
      screenshots: [
        'https://picsum.photos/seed/travelly-s1/800/1200',
        'https://picsum.photos/seed/travelly-s2/800/1200',
      ],
    },
    {
      title: 'Artisan Portfolio',
      slug: 'artisan-portfolio',
      description: 'A sleek and minimal portfolio website for a professional photographer.',
      fullDescription: 'This project involved creating a custom portfolio website for a photographer to showcase their work. The design is clean and image-focused, with a masonry grid layout and a custom lightbox for viewing high-resolution images. It was built using Gatsby for fast performance.',
      image: 'https://picsum.photos/seed/artisan/1200/800',
      hint: 'website photography',
      tags: ['Gatsby', 'React', 'Web Development', 'Portfolio'],
      category: 'web',
      link: '#',
      screenshots: [
        'https://picsum.photos/seed/artisan-s1/1200/800',
        'https://picsum.photos/seed/artisan-s2/1200/800',
      ],
    },
    {
      title: 'Zenith Finance App',
      slug: 'zenith-finance',
      description: 'A mobile banking app UI kit designed for clarity and ease of use.',
      fullDescription: 'Zenith is a UI kit for a modern banking application. The design prioritizes clarity and accessibility, with a clean layout, large typography, and intuitive navigation. The kit includes screens for all common banking tasks, such as transfers, payments, and account management.',
      image: 'https://picsum.photos/seed/zenith/1200/800',
      hint: 'mobile finance',
      tags: ['UI Kit', 'Sketch', 'Mobile App', 'Fintech'],
      category: 'mobile',
      link: '#',
      screenshots: [
        'https://picsum.photos/seed/zenith-s1/800/1200',
        'https://picsum.photos/seed/zenith-s2/800/1200',
        'https://picsum.photos/seed/zenith-s3/800/1200',
      ],
    },
    {
      title: 'RecipeFinder',
      slug: 'recipe-finder',
      description: 'A web application for discovering and saving recipes, built with Vue.js.',
      fullDescription: 'RecipeFinder is a web app that allows users to search for recipes from a large database, filter by ingredients or dietary restrictions, and save their favorites to a personal collection. It was built using Vue.js and the Spoonacular API.',
      image: 'https://picsum.photos/seed/recipe/1200/800',
      hint: 'website food',
      tags: ['Vue.js', 'Web App', 'API Integration'],
      category: 'web',
      link: '#',
      screenshots: [
        'https://picsum.photos/seed/recipe-s1/1200/800',
      ],
    },
    {
      title: 'Cygnus Icon Set',
      slug: 'cygnus-icons',
      description: 'A custom set of 100+ line icons designed for use in web and mobile applications.',
      fullDescription: 'Cygnus is a cohesive set of professional-grade icons designed with a consistent line weight and style. The set covers a wide range of common UI actions and objects, and each icon is provided in multiple formats (SVG, PNG) for easy integration into any project.',
      image: 'https://picsum.photos/seed/cygnus/1200/800',
      hint: 'icons minimal',
      tags: ['Iconography', 'Design System', 'SVG'],
      category: 'design',
      link: '#',
      screenshots: [],
    },
    {
      title: 'EventHorizon Conference',
      slug: 'eventhorizon-conf',
      description: 'A conference website with features for speaker bios, schedules, and ticket sales.',
      fullDescription: 'This is a landing page and registration portal for a fictional tech conference. The website was built to be fast, accessible, and easy to navigate, providing all necessary information for potential attendees. It includes integration with a ticketing platform.',
      image: 'https://picsum.photos/seed/event/1200/800',
      hint: 'website event',
      tags: ['Web Development', 'Next.js', 'Events'],
      category: 'web',
      link: '#',
      screenshots: [
        'https://picsum.photos/seed/event-s1/1200/800',
      ],
    }
  ];
