
// @ts-nocheck
// This file is autogenerated by Firebase Studio. All changes will be overwritten.
//prettier-ignore
const firebaseConfig = {
  "projectId": "studio-1131826709-e51a3",
  "appId": "1:124953614563:web:9c9fad83700296093a4dd6",
  "apiKey": "AIzaSyCb22IpzoJzfW_J-cmjnqo9Sk0iJaa3aXo",
  "authDomain": "studio-1131826709-e51a3.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "124953614563",
  "storageBucket": "studio-1131826709-e51a3.appspot.com"
};

export { firebaseConfig };
